apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: myapp
      image: "nginx:latest"
---
apiVersion: v1
kind: Pod
metadata:
  name: httpd
spec:
  containers:
    - name: myapp
      image: "httpd:latest"
---

