apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: myapp
      image: "anurag1829/github-action-test:9ddd5b688d8dae54386710c057a5370f00818999"
---
apiVersion: v1
kind: Pod
metadata:
  name: httpd
spec:
  containers:
    - name: myapp
      image: "httpd:latest"
---

